# Generated by Django 4.2.17 on 2025-03-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_collegeregistrar_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeregistrar',
            name='role',
            field=models.CharField(default='Registrar', max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='role',
            field=models.CharField(default='Lecturer', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.CharField(default='Student', max_length=100),
        ),
    ]
