# Generated by Django 4.2.17 on 2025-03-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_collegeregistrar_role_alter_lecturer_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='attachment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
